export enum AppErrorCode {
  // General errors
  OK = "OK",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  BAD_REQUEST = "BAD_REQUEST",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",

  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED",

  // User Errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_IN_USE = "EMAIL_IN_USE",

  // Files
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  TOO_MANY_FILES = "TOO_MANY_FILES",
  FILE_TOO_BIG = "FILE_TOO_BIG",
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",

  // Country Errors
  COUNTRY_NOT_FOUND = "COUNTRY_NOT_FOUND",
  COUNTRY_NAME_IN_USE = "COUNTRY_NAME_IN_USE",

  //Coin Errors
  COIN_NOT_FOUND = "COIN_NOT_FOUND",
}
